### ISSUE TITLE
Content jumping

### ISSUE THREAD

**Issue by Espumisan** [rhwilr/vue-nestable#12] opened 2019-01-29 14:10 UTC
Hey, I don't have all nestable items in the same height and when i'm trying to drag smaller item on to higher item it starts jumping up and down.

Video: https://www.screencast.com/t/f4xWxtOglF2b

**Comment by rhwilr** [comment] 2019-02-01 09:50
Thanks for this bug report.
I am working on a fix for this, I could fix it on the desktop, but unfortunately, it seems to be quiet difficult to fix this for mobile since some essential information is missing in the `TouchEvent`.
I will need to spend some more time investigating.

**Comment by Espumisan** [comment] 2019-02-01 13:31
Thanks! Hope you will fix this soon! :)

**Comment by rhwilr** [comment] 2019-02-05 14:36
The temporary fix is available in [2.1.0](https://github.com/rhwilr/vue-nestable/releases/tag/2.1.0). Keep in mind that the issue is only fixed for deskop-browsers and currently does not work on mobile. 

I'm going to close this issue and track the mobile improvement in #15

**Closed by rhwilr** 2019-02-05 14:36 UTC
