### ISSUE TITLE
Unable to drag in Chrome desktop

### ISSUE THREAD

**Issue by samlachance** [rhwilr/vue-nestable#107] opened 2021-04-01 17:37 UTC
Hello and thanks for the excellent component.

I've encountered an issue where I'm unable to drag items in the component when using Chrome. I am, however, able to use the component as expected with firefox AND Chrome mobile emulator (using dev tools). To make things more puzzling, I am able to use vue-nestable's example site with all browsers including Chrome. No errors occur either.

I'm kind of stumped at this point and was wondering if any of the details of this scenario might ring some bells with more experienced users. For what it's worth, here's what my view code looks like:

```
    vue-nestable(v-model="menu" ref="vueNestable" :maxDepth="3")
      vue-nestable-handle(slot-scope="{ item }" :item="item")
        mm-nestable-item(
          v-model="item"
          @destroy="destroyItem"
          :menuDatasets="menuDatasets")
```
FF Versions used: 86.0.1
Chrome versions used: 89.0.4389.90, 91.0.4455.2
OS: Arch linux

Thanks,
Sam

**Comment by samlachance** [comment] 2021-04-01 18:44
I've made another discovery. It appears to work correctly in Chrome desktop under a couple of strange conditions:

1. If I highlight everything on the page the dragging works as expected. If I deselect the content of the page then it stops working.
2. There are rare cases where I am able to "grab" the container (I'm not sure exactly what to call this but it's similar to how you can 'drag' images, links, etc on a page). If I'm able to drag and release, then the component starts to work as expected.

**Comment by htmljosh** [comment] 2021-04-03 00:09
I'm having the same problem here. I'm wondering if a chrome update caused this. I use firefox but a buddy just pointed out to me it doesn't work in chrome. 

Love the plugin though.

**Comment by rhwilr** [comment] 2021-05-01 08:27
Does this issue still persist for you? I tried it in various Chromium based browsers (Chrome, Chromium, Vivaldi) and I don't expedience this issue.

**Comment by htmljosh** [comment] 2021-05-01 19:29
Yeah, still having this issue. To add some more information, the way I am currently using it is like this (maybe samlachance has a similar configuration):

- `<vue-nestable>` inside a `<ul>` 
- `<li>` tag with another nested `<ul>` inside `<vue-nestable-handle>` 
- Note: I am still able to drag and drop if I click and drag on an anchor element, for instance: `<li><a @click="removeItem(item.index)">Remove</a></li>`

Thanks!

**Comment by samlachance** [comment] 2021-05-04 19:39
I am also still experiencing the issue. I'll try to recreate what @htmljosh noted.

**Comment by samlachance** [comment] 2021-07-19 17:37
I was able to restore draggability in chrome by adding this CSS rule on the direct child element of `vue-nestable-handle`:

```
pointer-events: none;
```

@htmljosh

**Comment by rhwilr** [comment] 2021-08-05 20:20
Closing since it seems to be an issue with implementation and is not reproducible with a simple app (demo application).

**Closed as completed by rhwilr** 2021-08-05 20:20 UTC
