### ISSUE TITLE
It doesn't operate well when using inside an element having its own overlflow-y:scroll

### ISSUE THREAD

**Issue by minhtu-cloudtek** [rhwilr/vue-nestable#10] opened 2018-12-28 21:02 UTC
I realized that when I put the component in an element having its own scroll bar (overflow-y:scroll), the margin of ".nestable-drag-layer .nestable-list" was wrongly calculated to simulate the drag and drop animation.

Is there any solution for me?

**Comment by rhwilr** [comment] 2018-12-30 18:59
Hi @minhtu-cloudtek 
Can you provide a code example that shows the problem?

You can use my codesandbox template if you want. https://codesandbox.io/s/pk3923rwz0

**Comment by rhwilr** [comment] 2019-01-15 13:15
@minhtu-cloudtek Does this issue still affect you or did you find a solution to it?
I could not reproduce it, so if you could provide an example that shows the problem? That would be great.

**Comment by rhwilr** [comment] 2019-01-31 15:56
Could be related to https://github.com/rhwilr/vue-nestable/issues/12.

**Comment by rhwilr** [comment] 2019-02-05 14:42
Closing this issue for the lack of clarification. 
Issue #12 and #15 are probably related. If not, feel free to leave a comment and I will reopen it.

**Closed by rhwilr** 2019-02-05 14:42 UTC
